### ISSUE TITLE
how to config tessdata_best for my mrz project 

### ISSUE THREAD

**Issue by Faran-khan000** [tesseract-ocr/tessconfigs#1]
Hello, I am stuck in the configuration of tessdata_best. By default, my tessaract ocr is using tessdata but I need tessdata_best for accuracy. Can you tell me how to configure tessdata_best in python? 
Thanks and regards
FaranKhan.

**Comment by stweil** [comment]
You won't get better accuracy with tessdata_best. I suggest to use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for additional questions.
